version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run webpack
  pre_build:
    commands:
      - npm test
artifacts:
  files:
    - index.html
    - favicon.ico
    - resources/Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
